development:
  secret_key_base: bade40edac87ad3d1406e13be3d4304ebed0408a091b3fe9d6aab27f8c28f405cb1d06939f77cb04b640d09e0b4aa2acab46cdc5ec91da18f1d1322f8deb9f16
  twitter_consumer_key: <%= ENV['TWITTER_CONSUMER_KEY'] %>
  twitter_consumer_secret: <%= ENV['TWITTER_CONSUMER_SECRET'] %>

test:
  secret_key_base: 9f27f5043e0493b9206f350c434253c187a6a86f7026a171f4edf37a9e7bb43d38a9b41f90b58605ecafedcee5f497c3a4416b919de82696fcab0439211f2156

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_consumer_key: <%= ENV['TWITTER_CONSUMER_KEY'] %>
  twitter_consumer_secret: <%= ENV['TWITTER_CONSUMER_SECRET'] %>
